config/routes.rb
SaasApplication::Application.routes.draw do

  resources :measures

  resources :stationeryrequests

  resources :hotelsupplies

  resources :taxirequests

  resources :employees
  resources :sessions
  resources :companies

  get 'login', :to => "sessions#new"
  get 'logout', :to => "sessions#destroy"
  post 'login', :to => "sessions#create"
  get "welcome/index"
  get 'home', :to => "home#index"
  get 'profile', :to => "employees#show"

  root :to => 'welcome#index'

end

app/models/hotelsupply.rb
class Hotelsupply < ActiveRecord::Base
  attr_accessible :cost, :name, :num
  has_many :hotelsuppliesrequests
  validates_associated :hotelsuppliesrequests
  has_many :stationeryrequests, :through => :hotelsuppliesrequests
end

app/controllers/hotelsupplies_controller.rb
class HotelsuppliesController < ApplicationController
  before_filter :require_login
  # GET /hotelsupplies
  # GET /hotelsupplies.json
  def index
    @hotelsupplies = Hotelsupply.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hotelsupplies }
      format.pdf do
        pdf = HotelsupplyPdf.new(@hotelsupplies, view_context)
        send_data pdf.render, filename: "hotelsupplies_#{Time.now.strftime('%d/%m/%Y')}.pdf", type: "application/pdf"
      end
    end
  end

  # GET /hotelsupplies/1
  # GET /hotelsupplies/1.json
  def show
    @hotelsupply = Hotelsupply.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hotelsupply }
    end
  end

  # GET /hotelsupplies/new
  # GET /hotelsupplies/new.json
  def new
    @hotelsupply = Hotelsupply.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hotelsupply }
    end
  end

  # GET /hotelsupplies/1/edit
  def edit
    @hotelsupply = Hotelsupply.find(params[:id])
  end

  # POST /hotelsupplies
  # POST /hotelsupplies.json
  def create
    @hotelsupply = Hotelsupply.new(params[:hotelsupply])

    respond_to do |format|
      if @hotelsupply.save
        format.html { redirect_to @hotelsupply, notice: 'Hotelsupply was successfully created.' }
        format.json { render json: @hotelsupply, status: :created, location: @hotelsupply }
      else
        format.html { render action: "new" }
        format.json { render json: @hotelsupply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hotelsupplies/1
  # PUT /hotelsupplies/1.json
  def update
    @hotelsupply = Hotelsupply.find(params[:id])

    respond_to do |format|
      if @hotelsupply.update_attributes(params[:hotelsupply])
        format.html { redirect_to @hotelsupply, notice: 'Hotelsupply was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hotelsupply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotelsupplies/1
  # DELETE /hotelsupplies/1.json
  def destroy
    @hotelsupply = Hotelsupply.find(params[:id])
    @hotelsupply.destroy

    respond_to do |format|
      format.html { redirect_to hotelsupplies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/hotelsupplies_helper.rb
module HotelsuppliesHelper
end

app/views/hotelsupplies/_form.html.erb
<%= form_for(@hotelsupply) do |f| %>
  <% if @hotelsupply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hotelsupply.errors.count, "error") %> prohibited this hotelsupply from being saved:</h2>

      <ul>
      <% @hotelsupply.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :num %><br />
    <%= f.number_field :num %>
  </div>
  <div class="field">
    <%= f.label :cost %><br />
    <%= f.number_field :cost %>
  </div>
  <div class="actions">
    <%= f.submit 'Добавить' %>
  </div>
<% end %>

app/views/hotelsupplies/edit.html.erb
<h1>Редактирование предмета</h1>

<%= render 'form' %>

<%= link_to 'Просмотр', @hotelsupply %> |
<%= link_to 'Назад', hotelsupplies_path %>

app/views/hotelsupplies/index.html.erb
<div id="add_request">
  <%= link_to 'Заявки на канц. принадлежности', stationeryrequests_path %> | <%= link_to 'Отчет-список ТМЦ на складе', '/hotelsupplies.pdf' %>
</div>
<div style="clear:both;"></div>
<h1>Товарно-материальные ценности на складе</h1>

<table>
  <tr>
	<th>ID</th>
    <th>Наименование</th>
    <th>Количество</th>
    <th>Цена за единицу(руб.)</th>
    <th></th>
    <th></th>
  </tr>

<% @hotelsupplies.each do |hotelsupply| %>
  <tr>
	<td><%= hotelsupply.id %></td>
    <td><%= hotelsupply.name %></td>
    <td><%= hotelsupply.num %></td>
    <td><%= hotelsupply.cost %></td>
    <td><%= link_to 'Редактировать', edit_hotelsupply_path(hotelsupply) %></td>
    <td><%= link_to 'Удалить', hotelsupply, method: :delete, data: { confirm: 'Вы уверены, что хотите удалить этот предмет со склада?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Поступление товара', new_hotelsupply_path %>

app/views/hotelsupplies/new.html.erb
<h1>Поступление нового товара</h1>

<%= render 'form' %>

<%= link_to 'Назад', hotelsupplies_path %>

app/views/hotelsupplies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Наименование:</b>
  <%= @hotelsupply.name %>
</p>

<p>
  <b>Количество:</b>
  <%= @hotelsupply.num %>
</p>

<p>
  <b>Цена за единицу(руб.):</b>
  <%= @hotelsupply.cost %>
</p>


<%= link_to 'Редактировать', edit_hotelsupply_path(@hotelsupply) %> |
<%= link_to 'Назад', hotelsupplies_path %>