config/routes.rb
SaasApplication::Application.routes.draw do

  resources :measures

  resources :stationeryrequests

  resources :hotelsupplies

  resources :taxirequests

  resources :employees
  resources :sessions
  resources :companies

  get 'login', :to => "sessions#new"
  get 'logout', :to => "sessions#destroy"
  post 'login', :to => "sessions#create"
  get "welcome/index"
  get 'home', :to => "home#index"
  get 'profile', :to => "employees#show"

  root :to => 'welcome#index'

end

app/models/taxirequest.rb
class Taxirequest < ActiveRecord::Base
  require 'uri'
  require 'net/http'
  attr_accessible :destination, :room, :arrival_date, :arrival_time, :payment_method, :cost, :order_number, :guest_name, :status
  belongs_to :employee
  
  validates :destination, :arrival_date, :arrival_time, :payment_method, :presence => true
  #validates_presence_of :employee_id, :on => :create
  validates_numericality_of :cost, :on => :update
  #validates_numericality_of :order_number, :on => :update
  
  def self.call_a_taxi(params)
    # этот метод должен отправлять post-запрос на сервер заказа такси и возвращать результат - номер заказа
    #order_number = Net::HTTP.post_form(URI.parse('http://www.2212212.ru/onlajn_zakaz_taksi.htm'), params)
    order_number = 1000000 + rand(1000000)
    return order_number
  end
  
  def self.add_request(params, employee_id, order_number)
    # этот метод создает объект класса Taxirequest и сохраняет его в БД
    taxirequest = self.new(params)
    taxirequest.employee_id = employee_id
    taxirequest.order_number = order_number
    return taxirequest
  end
  
end

app/controllers/taxirequests_controller.rb
# encoding: utf-8
class TaxirequestsController < ApplicationController
  before_filter :require_login
  # GET /taxirequests
  # GET /taxirequests.json
  def index
    end_date = Time.now.to_date+1
    start_date = Time.now.to_date-Time.now.to_date.day+1
    #узнать кол-во всех заявок на такси за месяц
    @all_taxirequests = Taxirequest.where(:created_at => start_date..end_date)
    @taxirequests = Taxirequest.where(:arrival_date => Time.now.to_date, :status => 0)
    #заявки такси на вчера
    @taxirequests_yesterday = Taxirequest.where(:arrival_date => Time.now.to_date-1, :status => 0)
    #заявки такси на 2 дня назад
    @taxirequests_2days_ago = Taxirequest.where(:arrival_date => Time.now.to_date-2, :status => 0)
    if(params[:id])
      a = [ ]
      # b - временный массив
      b = [ ]
      i = 0
      @closedtaxirequests = Taxirequest.where(:arrival_date => Time.now.to_date-params[:id].to_i, :status => 1).select('employee_id,payment_method,destination,arrival_time')
      @closedtaxirequests.each do |taxirequest|
        employee = Employee.find(taxirequest.employee_id)
        b[0] = employee.employee
        b[1] = taxirequest.payment_method
        b[2] = taxirequest.destination
        b[3] = taxirequest.arrival_time.strftime('%H:%M')
        a[i] = b
        b = [ ]
        i += 1
      end
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: a }
      format.pdf do
        pdf = TaxirequestPdf.new(@all_taxirequests, view_context)
        send_data pdf.render, filename: "taxirequests_#{Time.now.strftime('%d/%m/%Y')}.pdf", type: "application/pdf"
      end
    end
  end

  # GET /taxirequests/1
  # GET /taxirequests/1.json
  def show
    @taxirequest = Taxirequest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @taxirequest }
    end
  end

  # GET /taxirequests/new
  # GET /taxirequests/new.json
  def new
    @taxirequest = Taxirequest.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @taxirequest }
    end
  end

  # GET /taxirequests/1/edit
  def edit
    @taxirequest = Taxirequest.find(params[:id])
  end

  # POST /taxirequests
  # POST /taxirequests.json
  def create
    # Вызвать такси
    @order_number = Taxirequest.call_a_taxi(params[:taxirequest])
    # Разместить заявку на такси в таблице taxirequests
    @taxirequest = Taxirequest.add_request(params[:taxirequest], session[:employee_id], @order_number)
    #@taxirequest = Taxirequest.new(params[:taxirequest])

    respond_to do |format|
      if @taxirequest.save
        format.html { redirect_to @taxirequest, notice: 'Taxirequest was successfully created.'+@response }
        format.json { render json: @taxirequest, status: :created, location: @taxirequest }
      else
        format.html { render action: "new" }
        format.json { render json: taxirequest.errors, status: :unprocessable_entity }
      end
    end

  end

  # PUT /taxirequests/1
  # PUT /taxirequests/1.json
  def update
    @taxirequest = Taxirequest.find(params[:id])

    respond_to do |format|
      if @taxirequest.update_attributes(params[:taxirequest])
        format.html { redirect_to @taxirequest, notice: 'Taxirequest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @taxirequest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /taxirequests/1
  # DELETE /taxirequests/1.json
  def destroy
    @taxirequest = Taxirequest.find(params[:id])
    @taxirequest.destroy

    respond_to do |format|
      format.html { redirect_to taxirequests_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/taxirequests_helper.rb
module TaxirequestsHelper
end

app/views/taxirequests/_form.html.erb
<%= form_for(@taxirequest) do |f| %>
  <% if @taxirequest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@taxirequest.errors.count, "error") %> prohibited this taxirequest from being saved:</h2>

      <ul>
      <% @taxirequest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :arrival_date %><br />
    <%= f.date_select :arrival_date, :order => [:day, :month, :year] %>
    <%= f.label :arrival_time %>
    <%= f.time_select :arrival_time, :minute_step => 5, :default => Time.now %>
  </div>
  <div class="field">
    <%= f.label :destination %><br />
    <%= f.text_field :destination %>
  </div>
  <div class="field">
    <%= f.label :payment_method %><br />
    <%= f.select(:payment_method, [['car', 'car'], ['opera', 'Opera']]) %>
  </div>
  <div class="field">
    <%= f.label :room %><br />
    <%= f.text_field :room %>
  </div>
<% # если текущая страница - редактирование %>
<% if params[:action] == 'edit' %>
  <div class="field">
	<%= f.label :order_number %><br />
    <%= f.text_field :order_number %>
  </div>
  <div class="field">
	<%= f.label :cost %><br />
    <%= f.text_field :cost %>
  </div>
  <div class="field">
	<%= f.label :guest_name %><br />
    <%= f.text_field :guest_name %>
  </div>
  <div class="field">
	<%= f.label :status %><br />
    <%= f.check_box :status %>
  </div>
<% end %>
  <div class="actions">
    <%= f.submit 'Выполнить' %>
  </div>
<% end %>

app/views/taxirequests/edit.html.erb
<h1>Редактирование заказа</h1>

<%= render 'form' %>

<%= link_to 'Подробнее', @taxirequest %> |
<%= link_to 'Назад', taxirequests_path %>

app/views/taxirequests/index.html.erb
<div id="add_request">
  <%= link_to 'Заказать такси', new_taxirequest_path %> | <%= link_to 'Ежемесячный отчет', '/taxirequests.pdf' %>
</div>
<div style="clear:both;"></div>
<h3>Заявки такси на сегодня (<%= Time.now.strftime('%d-%m-%Y') %>)</h3>
<ul class="list_for_day0">
  <li>
    <ul class="head">
      <li>кто заказывал</li>
      <li>метод оплаты</li>
      <li>пункт назначения</li>
      <li>время подачи</li>
    </ul>
  </li>

  <% @taxirequests.each do |taxirequest| %>
  <li>
    <ul class="taxi_request">
	  <li><%= taxirequest.employee.employee %></li>
	  <li><%= taxirequest.payment_method %></li>
	  <li><%= taxirequest.destination %></li>
	  <li><%= taxirequest.arrival_time.strftime('%H:%M') %></li>
      <li><%= link_to 'Редактировать', edit_taxirequest_path(taxirequest) %></li>
      <li><%= link_to 'Отменить', taxirequest, method: :delete, 
			data: { confirm: 'Вы уверены, что хотите отменить заказ? Для отмены заказа сначала позвоните 2212212 и скажите № заказа!' } %></td>
    </ul>
  </li>
  <% end %>
  <li><span id="0" class="closed_req">Показать закрытые заявки</span></li>
</ul>
<hr />
<h3>Заявки такси на вчера (<%= (Time.now.to_date-1).strftime('%d-%m-%Y') %>)</h3>
<ul class="list_for_day1">
  <li>
    <ul class="head">
      <li>кто заказывал</li>
      <li>метод оплаты</li>
      <li>пункт назначения</li>
      <li>время подачи</li>
    </ul>
  </li>

  <% @taxirequests_yesterday.each do |taxirequest| %>
  <li>
    <ul class="taxi_request">
	  <li><%= taxirequest.employee.employee %></li>
	  <li><%= taxirequest.payment_method %></li>
	  <li><%= taxirequest.destination %></li>
	  <li><%= taxirequest.arrival_time.strftime('%H:%M') %></li>
      <li><%= link_to 'Редактировать', edit_taxirequest_path(taxirequest) %></li>
      <li><%= link_to 'Отменить', taxirequest, method: :delete, 
			data: { confirm: 'Вы уверены, что хотите отменить заказ? Для отмены заказа сначала позвоните 2212212 и скажите № заказа!' } %></td>
    </ul>
  </li>
  <% end %>
  <li><span id="1" class="closed_req">Показать закрытые заявки</span></li>
</ul>
<hr />
<h3>Заявки такси на <%= (Time.now.to_date-2).strftime('%d-%m-%Y') %></h3>
<ul class="list_for_day2">
  <li>
    <ul class="head">
      <li>кто заказывал</li>
      <li>метод оплаты</li>
      <li>пункт назначения</li>
      <li>время подачи</li>
    </ul>
  </li>

  <% @taxirequests_2days_ago.each do |taxirequest| %>
  <li>
    <ul class="taxi_request">
	  <li><%= taxirequest.employee.employee %></li>
	  <li><%= taxirequest.payment_method %></li>
	  <li><%= taxirequest.destination %></li>
	  <li><%= taxirequest.arrival_time.strftime('%H:%M') %></li>
      <li><%= link_to 'Редактировать', edit_taxirequest_path(taxirequest) %></li>
      <li><%= link_to 'Отменить', taxirequest, method: :delete, 
			data: { confirm: 'Вы уверены, что хотите отменить заказ? Для отмены заказа сначала позвоните 2212212 и скажите № заказа!' } %></td>
    </ul>
  </li>
  <% end %>
  <li><span id="2" class="closed_req">Показать закрытые заявки</span></li>
</ul>

app/views/taxirequests/new.html.erb
<h1>Заказ такси</h1>

<%= render 'form' %>

<%= link_to 'Назад', taxirequests_path %>

app/views/taxirequests/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Редактировать', edit_taxirequest_path(@taxirequest) %> |
<%= link_to 'Назад', taxirequests_path %>